#!/bin/bash
find -type f -name "*.gif" -printf "%f\n" | rev | cut -d'.' -f 2cat > 103-the_biggest_fan
#!/bin/bash
tail -n +2 | cut -f1 | sort | uniq -c | sort -nr | head -11 | tr -s ' ' | cut -d' ' -f3
